name: publish to production server

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Copy to production server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.privateKey }}
        with:
          source: "*"
          target: "~/it/clash-configs/"
          overwrite: true

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.privateKey }}
          script: cd it/clash-configs && git secret reveal -p ${{ secrets.GPG_PASSPHRASE }}
