name: publish to production server

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: do git clone && reveal secret files via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.privateKey }}
          script: cd it && rm -rf clash-configs && git clone https://github.com/NUCSSA/clash-policy-configs.git clash-configs && cd clash-configs && git secret reveal -p ${{ secrets.GPG_PASSPHRASE }}
